steps:
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/stern-backend:${COMMIT_SHA}
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--network=cloudbuild'
      - '--path=stern-backend'
    id: Buildpack
    entrypoint: pack
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - --destination=${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/stern-backend:${COMMIT_SHA}
    - --dockerfile=stern-backend/Dockerfile
    - --cache=true
    - --cache-ttl=3h
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/stern-backend:${COMMIT_SHA}
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/stern-backend:${COMMIT_SHA}
  - ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/stern-backend/cache:${COMMIT_SHA}
options:
  logging: CLOUD_LOGGING_ONLY
tags:
  - stern-backend
