steps:
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - us-east4-docker.pkg.dev/hacknjit2023-strawhats/cloud-run-source-deploy/hacknjit-2023/stern-backend:${COMMIT_SHA}
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--network=cloudbuild'
      - '--path=stern-backend'
    id: Buildpack
    entrypoint: pack
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - --destination=us-east4-docker.pkg.dev/hacknjit2023-strawhats/cloud-run-source-deploy/hacknjit-2023/stern-backend:${COMMIT_SHA}
    - --dockerfile=stern-backend/Dockerfile
    - --cache=true
    - --cache-ttl=3h
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - stern-backend
      - '--platform=managed'
      - >-
        --image=us-east4-docker.pkg.dev/hacknjit2023-strawhats/cloud-run-source-deploy/hacknjit-2023/stern-backend:${COMMIT_SHA}
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=us-east4'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - us-east4-docker.pkg.dev/hacknjit2023-strawhats/cloud-run-source-deploy/hacknjit-2023/stern-backend:${COMMIT_SHA}
  - us-east4-docker.pkg.dev/hacknjit2023-strawhats/cloud-run-source-deploy/hacknjit-2023/stern-backend/cache:${COMMIT_SHA}
options:
  logging: CLOUD_LOGGING_ONLY
