steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'bow-frontend'
    args: ['install']
    id: Setup
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'bow-frontend'
    args: ['run', 'build']
    id: Build
  - name: 'gcr.io/$PROJECT_ID/firebase'
    dir: 'bow-frontend/build'
    id: Deploy
    args:
      - deploy
      - --only=hosting
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
tags:
  - bow-frontend
