steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'bow-frontend/my-app'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'bow-frontend/my-app'
    args: ['run', 'build']
  - name: 'gcr.io/$PROJECT_ID/firebase'
    dir: 'bow-frontend/my-app'
    args:
      - deploy
      - --only=hosting
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY